name: frontendd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.3
  shared_preferences: ^2.5.4
  flutter_riverpod: ^3.1.0
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  flutter_ruler_picker: ^1.0.6
  flutter_scale_ruler: ^1.0.0
  numberpicker: ^2.1.2
  state_notifier: ^1.0.0
  lottie: ^3.3.2
  intl: ^0.20.2
  infinite_carousel: ^1.1.1
  sidebarx: ^0.17.2
  sliding_clipped_nav_bar: ^3.1.1
  freezed_annotation: ^2.4.1
  awesome_snackbar_content: ^0.1.8
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.12.0
  syncfusion_flutter_sliders: ^32.1.24
  scroll_wheel_selector: ^0.0.4
  fl_chart: ^1.1.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  permission_handler: ^11.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.4.5
  build_runner: ^2.4.6
  on_popup_window_widget: ^0.0.14

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
